"""
Application domain constants.

Defines valid application statuses for the Artemis workflow.
"""

APPLICATION_STATUS_SAVED = "saved"
APPLICATION_STATUS_READY = "ready"
APPLICATION_STATUS_NEEDS_REVIEW = "needs_review"
APPLICATION_STATUS_SUBMITTED = "submitted"
APPLICATION_STATUS_FAILED = "failed"

APPLICATION_STATUSES = {
    APPLICATION_STATUS_SAVED,
    APPLICATION_STATUS_READY,
    APPLICATION_STATUS_NEEDS_REVIEW,
    APPLICATION_STATUS_SUBMITTED,
    APPLICATION_STATUS_FAILED,
}