"""
Application domain constants.

Defines valid application statuses for the Artemis workflow.
"""

APPLICATION_STATUS_SAVED = "saved"
APPLICATION_STATUS_READY = "ready"
APPLICATION_STATUS_NEEDS_REVIEW = "needs_review"

# Pipeline stage statuses (inspect → plan → fill)
APPLICATION_STATUS_QUEUED = "queued"
APPLICATION_STATUS_INSPECTING = "inspecting"
APPLICATION_STATUS_INSPECTED = "inspected"
APPLICATION_STATUS_PLANNING = "planning"
APPLICATION_STATUS_PLANNED = "planned"
APPLICATION_STATUS_FILLING = "filling"
APPLICATION_STATUS_FILLED = "filled"
APPLICATION_STATUS_AWAITING_SUBMISSION = "awaiting_submission"

APPLICATION_STATUS_SUBMITTED = "submitted"
APPLICATION_STATUS_FAILED = "failed"

APPLICATION_STATUSES = {
    APPLICATION_STATUS_SAVED,
    APPLICATION_STATUS_READY,
    APPLICATION_STATUS_NEEDS_REVIEW,
    APPLICATION_STATUS_QUEUED,
    APPLICATION_STATUS_INSPECTING,
    APPLICATION_STATUS_INSPECTED,
    APPLICATION_STATUS_PLANNING,
    APPLICATION_STATUS_PLANNED,
    APPLICATION_STATUS_FILLING,
    APPLICATION_STATUS_FILLED,
    APPLICATION_STATUS_AWAITING_SUBMISSION,
    APPLICATION_STATUS_SUBMITTED,
    APPLICATION_STATUS_FAILED,
}